language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
install:
  - pip install -r requirements/dev.txt
script:
  - flake8 --ignore E501 passgen tests
  - py.test --cov=passgen tests/
  - coveralls
