language: python
python:
  - "3.8"
services:
  - docker
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - flake8 --ignore E501 passgen tests
  - py.test --cov=passgen tests/
  - coveralls
  - export VERSION=$(poetry version -s)
  - docker build -t toolen/passgen:$VERSION .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push toolen/passgen:$VERSION
