version: "3"
services: 
  passgen:
    # build: .
    # image: dockerimg.evelopers.com/dzakharov/passgen:0.0.1
    image: dzakharov/passgen:0.0.1
    restart: always
    environment:
      - GUNICORN_CMD_ARGS="-b 0.0.0.0:8181"
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 127.0.0.1:8080:80
